version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: Zefity
      POSTGRES_PASSWORD: 5332Dialog
      POSTGRES_DB: site
    ports:
      - "5432:5432"
  prediction:
    build:
      context: ./mysite
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      DEBUG: "False"
      DB_NAME: "site"
      DB_USER: "Zefity"
      DB_PASSWORD: "5332Dialog"
      DB_HOST: "postgres"
      DB_PORT: 5432