version: '3.8'

services:
  prediction:
    build:
      context: ./mysite
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      DEBUG: "False"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "5332Dialog"
      DB_HOST: "postgres"
      DB_PORT:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5332Dialog
      POSTGRES_DB: postgres
    ports:
      - "6423:5432"