# Generated by Django 5.0.2 on 2024-02-28 10:52

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FSHL', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='FSHL.category'),
        ),
        migrations.AddField(
            model_name='thing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thing', to='FSHL.category'),
        ),
        migrations.AddField(
            model_name='basket',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSHL.thing'),
        ),
    ]
